version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command:
      - gunicorn
      - mysite.wsgi:application
      - --bind
      - 0.0.0.0:8000
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    environment:
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
      - LC_ALL=en_US.UTF-8
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    volumes:
      - ./mysite/database:/app/database
      - ./mysite/staticfiles:/app/staticfiles
      - ./mysite/uploads:/app/uploads


  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /usr/share/nginx/html
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"


  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
      - certbot  # зависимость от certbot для корректной сборки nginx
    volumes:
      - ./mysite/staticfiles:/app/staticfiles
      - ./mysite/uploads:/app/uploads
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
      - ./nginx/html:/usr/share/nginx/html
    environment:
      - SERVER_NAME=${SERVER_NAME}
    env_file:
      - .env

