FROM nginx:latest

RUN apt-get update && apt-get install -y gettext-base

COPY nginx.conf.template /etc/nginx/templates/nginx.conf.template
RUN mkdir -p /etc/nginx/conf.d
COPY conf.d /etc/nginx/conf.d
COPY --from=certbot /etc/letsencrypt/options-ssl-nginx.conf /etc/letsencrypt/options-ssl-nginx.conf

CMD ["/bin/sh", "-c", "envsubst '$$SERVER_NAME' < /etc/nginx/templates/nginx.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]