version: "3.9"

services:
  app:
    build:
      dockerfile: ./Dockerfile
    command:
      - gunicorn
      - mysite.wsgi:application
      - --bind
      - 0.0.0.0:8000
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    volumes:
      - ./mysite/database:/app/database
      - ./mysite/staticfiles:/app/staticfiles
      - ./mysite/uploads:/app/uploads


  nginx:
      image: nginx:latest
      ports:
        - "80:80"
      volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
        - ./mysite/staticfiles:/app/staticfiles
        - ./mysite/uploads:/app/uploads
      depends_on:
        - app


#  grafana:
#    image: grafana/grafana:11.1.0
#    environment:
#      - GF_AUTH_ANONYMOUS_ENABLED=true
#      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
#    ports:
#      - "3000:3000"
#
#  loki:
#    image: grafana/loki:3.0.0
#    ports:
#      - "3100:3100"