# Generated by Django 5.1a1 on 2024-06-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0004_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="product",
            field=models.ManyToManyField(related_name="orders", to="shopapp.product"),
        ),
    ]
