# Generated by Django 5.1a1 on 2024-07-04 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0008_alter_order_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Order", "verbose_name_plural": "Orders"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
    ]
